on: [push, pull_request] # Todo push ou pull_request, essa ação será executada

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositorio do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 14


        - name: instalando as dependencias
          run: npm install

        - name: executando o lint para verificar se a erros
          run: npx eslint .
